### ISSUE TITLE
Add Deprecation Warnings for Project Renaming

### ISSUE THREAD

**Issue by koladev32** [koladev32/drf-apikey#58]
As part of our transition from `djangorestframework-simple-apikey` to `drf-apikey`, we need to add deprecation warnings to the old package. These warnings will alert users upon installation and usage that the package has been renamed and direct them to the new package.

### Objective

To ensure that all current users of `djangorestframework-simple-apikey` are aware of the name change and understand how to migrate to `drf-apikey`. This will help in a smooth transition and prevent confusion.

### Tasks

- [x] Update the package initialization code to include a Python `warnings.warn()` statement that fires when the package is imported.
- [x] Ensure that the warning message includes clear instructions on how to transition to the new package name and the starting version number.
- [x] Update the README and documentation to reflect the deprecation and point users to the new package.
- [x] Release a new version of the old package (`1.2.4`) with these warnings.

### Proposed Warning Message

When users import the old package, they should receive the following warning:

```python
import warnings
warnings.warn(
    "This package, 'djangorestframework-simple-apikey', has been renamed to 'drf-apikey' and will no longer be updated. "
    "Please switch to the new package to continue receiving updates and support. "
    "For more information and migration instructions, please visit: [New Package URL]",
    DeprecationWarning
)
